### ISSUE TITLE
Visual Feedback

### ISSUE THREAD

**Issue by allisonanne** [SIU-CS-435/RARE-production#18]
As a user I want to view task progress visually by a colored bar moving gradually from red to green.

1. User increments task, and the task changes colors.
2. User decrements task, and the task changes colors.

**Comment by ethanx94** [comment]
Recolor according to:
Divide progress/total, get a percentage, use this as the part of the gradient we want to be at.
Output a decimal less than 1 if not complete (Ex. 0.5), color red. Once you complete 1/1 (aka 1.0) color green.
Later we can scale the percentage to a gradient that runs from Red 0.0 to Green 1.0

**Comment by Griffon0129** [comment]
Idea for how this will work right now:
Use a Hex color code that will be placed on the background of the individual task.
0% = FF0000, 50% = FFFF00, 100% = 00FF00 then in between will be determined on the %
example: xFF=d255, say progress is 32/78=41%,  255*.41=104,  d104=x68  so the color would be FF6800 for this task.

Although this may get put off till later when the current GUI will be easier to use/access (use bootstrap instead of default style).

**Comment by ethanx94** [comment]
I've got most of it prepped and pulled to gh-pages.
git checkout gh-pages
git pull 
Take your algo and plug it in UserTaskList.aspx.cs under OnRowDataBound in the for-each. Good hack!

**Comment by Griffon0129** [comment]
Finished color feedback and even added 3 color schemes.
